edit_uri: ''
extra:
  social:
  - icon: fontawesome/brands/bitbucket
    link: https://bitbucket.org/inaccel
  - icon: fontawesome/brands/docker
    link: https://hub.docker.com/u/inaccel
  - icon: fontawesome/brands/github
    link: https://github.com/inaccel
  - icon: fontawesome/brands/linkedin
    link: https://linkedin.com/company/inaccel
  - icon: fontawesome/brands/medium
    link: https://medium.com/@inaccel
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/inaccel
  - icon: fontawesome/brands/youtube
    link: https://youtube.com/channel/UCzUcYE3p19_7UA33z3Bb9Mw
extra_css:
- https://cdnjs.cloudflare.com/ajax/libs/flexboxgrid/6.3.1/flexboxgrid.min.css
- assets/fonts/stylesheet.css
- assets/stylesheets/extra.css
- assets/stylesheets/load.css
- assets/stylesheets/paint.css
- assets/stylesheets/palette.css
- assets/stylesheets/papercups.css
extra_javascript:
- https://cdn.jsdelivr.net/npm/typed.js@2.0.11
- https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
- https://code.jquery.com/jquery-2.2.4.js
- assets/javascripts/load.js
- assets/javascripts/paint.js
- assets/javascripts/tabbed.js
- assets/javascripts/time.js
- assets/javascripts/youtube.js
google_analytics:
- UA-159948615-1
- auto
markdown_extensions:
- admonition
- attr_list
- codehilite
- footnotes
- meta
- pymdownx.arithmatex
- pymdownx.betterem:
    smart_enable: all
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
- pymdownx.inlinehilite
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences
- pymdownx.tabbed
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde
- toc:
    permalink: '-'
    toc_depth: 3
nav:
- 'Home': index.md
- 'Guides':
  - 'Get InAccel':
    - 'Overview': overview.md
    - 'Install':
      - 'Linux platforms': install/linux.md
      - 'Debian': install/debian.md
      - 'RPM': install/rpm.md
    - 'Setup':
      - 'InAccel repository': setup/repo.md
      - 'Dockerfile': setup/docker.md
      - 'Kubernetes': setup/kubernetes.md
    - 'Release Notes': release-notes.md
  - 'Get started':
    - 'Part 1: Orientation': get-started/index.md
    - 'Part 2: Setup the working environment': get-started/part2.md
    - 'Part 3: Deploy your bitstreams': get-started/part3.md
    - 'Part 4: Accelerate your app': get-started/part4.md
  - 'Develop with InAccel':
    - 'Overview': develop.md
    - 'Projects':
      - 'Apache Spark':
        - 'Run locally': project/spark/locally.md
        - 'Run in a cluster': project/spark/in-a-cluster.md
        - 'Machine Learning Examples': project/spark/ml-examples.md
      - 'Jupyter Notebook': project/jupyter/lab.md
      - 'Keras': project/keras.md
      - 'scikit-learn': project/scikit-learn.md
      - 'TF Quant Finance': project/tf-quant-finance.md
      - 'XGBoost': project/xgboost.md
- 'Reference':
  - 'File formats':
    - 'Bitstream file reference': reference/file-formats/bitstream.md
  - 'Command line reference':
    - 'InAccel CLI (inaccel)':
      - 'inaccel (base command)': reference/inaccel/index.md
      - 'inaccel bitstream *':
        - 'inaccel bitstream': reference/inaccel/bitstream/index.md
        - 'inaccel bitstream parse': reference/inaccel/bitstream/parse.md
        - 'inaccel bitstream install': reference/inaccel/bitstream/install.md
        - 'inaccel bitstream list': reference/inaccel/bitstream/list.md
        - 'inaccel bitstream remove': reference/inaccel/bitstream/remove.md
      - 'inaccel config *':
        - 'inaccel config': reference/inaccel/config/index.md
        - 'inaccel config repository': reference/inaccel/config/repository.md
    - 'InAccel Docker CLI reference':
      - 'docker inaccel (base subcommand)': reference/docker/inaccel/index.md
      - 'docker inaccel config': reference/docker/inaccel/config.md
      - 'docker inaccel down': reference/docker/inaccel/down.md
      - 'docker inaccel exec': reference/docker/inaccel/exec.md
      - 'docker inaccel logs': reference/docker/inaccel/logs.md
      - 'docker inaccel ps': reference/docker/inaccel/ps.md
      - 'docker inaccel run': reference/docker/inaccel/run.md
      - 'docker inaccel up': reference/docker/inaccel/up.md
  - 'API reference':
    - 'Coral API':
      - 'C (Core)': https://setup.inaccel.com/coral-api/?c
      - 'C++': https://setup.inaccel.com/coral-api/?cpp
      - 'Java': https://setup.inaccel.com/coral-api/?java
      - 'Python': https://setup.inaccel.com/coral-api/?python
  - 'Glossary':
    - 'accelerator': glossary/accelerator.md
    - 'bitstream': glossary/bitstream.md
    - 'container': glossary/container.md
    - 'container runtime': glossary/container-runtime.md
    - 'Coral': glossary/coral.md
    - 'device plugin': glossary/device-plugin.md
    - 'FPGA': glossary/fpga.md
    - 'InAccel': glossary/inaccel.md
    - 'InAccel Store': glossary/inaccel-store.md
    - 'repository': glossary/repository.md
- 'Samples':
  - 'Tutorial labs':
    - 'Rolling your own Bitstream Repository': labs/bitstream-repository.md
    - 'Zero to FPGAs using BinderHub': labs/binderhub-aws.md
    - 'Accelerate ML workflows on Katib': labs/katib.md
    - 'Build H2O models with the FPGA backend': labs/h2o.md
    - 'Using OpenShift for accelerated Data Analytics': labs/openshift-aws.md
    - 'Hybrid auto-scalable FPGA deployment': labs/auto-scaling-aws.md
    - 'Get Up and Running with FPGAs in Rancher Kubernetes Clusters': labs/rancher/index.md
plugins:
- awesome-pages
- git-revision-date-localized
- minify:
    minify_html: true
- redirects:
    redirect_maps:
      get-started/part1.md: get-started/index.md
- search
repo_url: https://github.com/inaccel
site_author: InAccel
site_description: InAccel is a product for you to build, ship and run FPGA accelerated applications
site_name: InAccel Documentation
site_url: https://docs.inaccel.com/
theme:
  custom_dir: theme
  features:
  - navigation.instant
  - navigation.tabs
  font:
    code: Roboto Mono
    text: Open Sans
  logo: assets/images/inaccel-docs-logo.svg
  name: material
  palette:
    accent: inaccel
    primary: inaccel
    scheme: default
